[package]
name = "rsquant-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
rsquant-tool = { path = "../rsquant-tool" }

proc-macro2 = "1.0.86"
quote = "1.0.36"
syn = "2.0.67"
