name: Lint

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - uses: pre-commit/action@v3.0.0

  check-rs:
    needs: pre-commit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download build image
        run: docker pull clux/muslrust:nightly

      - name: Test
        run: docker run -v $PWD:/volume --rm -t clux/muslrust:nightly bash -c 'cargo install cargo-nextest && cargo test'
